# Generated by Django 2.2.6 on 2019-10-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producte',
            options={'ordering': ['sub_categoria__categoria__nom', 'sub_categoria__nom', 'nom']},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('nom', 'categoria')},
        ),
    ]
