# Generated by Django 2.2.6 on 2019-10-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productes', '0002_auto_20191006_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='data_creacio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='darrera_modificacio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
